version: '3.8'

services:
  backend:
    container_name: lms-backend
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - "3000:3000"
    env_file: 
      - .env
    volumes:
      - ./:/app
    depends_on:
      - database
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  database:
    container_name: lms-database
    image: postgres:13
    env_file: 
      - .env
    ports:
      - "5432:5432"
    volumes:
      - lms-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    container_name: lms-redis
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  lms-pgdata:
